# NumPy: Complete Content Notes

## 1\. Overview of NumPy

**NumPy** stands for **Numerical Python**. It is a powerful Python library used for:

- numerical computations
    
- scientific computing
    
- working with arrays and matrices
    
- performing mathematical and statistical operations efficiently
    

NumPy is faster than normal Python lists because it is implemented in optimized C code and stores data in contiguous memory locations.

### Why NumPy is important

- supports large multi-dimensional arrays
    
- performs fast calculations
    
- provides many built-in mathematical functions
    
- used in data science, machine learning, AI, scientific programming, and analytics
    

### Features of NumPy

- efficient array object called `ndarray`
    
- less memory usage
    
- faster execution than Python lists
    
- supports vectorized operations
    
- supports broadcasting
    
- has mathematical, statistical, and linear algebra functions
    

### Importing NumPy

In [1]:
import numpy as np

# 2\. NumPy ndarray

The main object in NumPy is the **ndarray**, which means **N-dimensional array**.

It is a collection of elements of the same data type arranged in one or more dimensions.

### Examples

- 1D array → like a list
    
- 2D array → like a table or matrix
    
- 3D array → collection of matrices
    

### Example

In [2]:
import numpy as np
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


### 2D example

In [3]:
b = np.array([[1, 2], [3, 4]])
print(b)

[[1 2]
 [3 4]]


### Advantages of ndarray

- homogeneous data
    
- fast computation
    
- supports multi-dimensional data
    
- easy mathematical operations
    

* * *

# 3\. Datatypes in NumPy

In NumPy, all elements in an array usually have the **same datatype**.

### Common datatypes

- `int_` → integer
    
- `float_` → decimal numbers
    
- `bool_` → True/False
    
- `complex_` → complex numbers
    
- `str_` → strings
    

### Example

In [4]:
a = np.array([1, 2, 3], dtype=float)
print(a)

[1. 2. 3.]


### Checking datatype

In [5]:
print(a.dtype)

float64


### Why datatype matters

- memory efficiency
    
- accuracy of computation
    
- speed improvement
    

* * *

# 4\. Array Creation

Arrays in NumPy can be created in many ways.

## a) Using `np.array()`

In [6]:
a = np.array([1, 2, 3])

In [7]:
b = np.array([[1, 2], [3, 4]])

In [8]:
print(a)
print(b)

[1 2 3]
[[1 2]
 [3 4]]


In [9]:
print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
print(np.ones((2, 2)))

[[1. 1.]
 [1. 1.]]


## Using `empty()`

Creates array without initializing entries properly.

In [11]:
print(np.empty((2, 2)))

[[1. 1.]
 [1. 1.]]


## Using `arange()`

Creates array with a range of values.

In [12]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

## Using `linspace()`

Creates equally spaced values between start and end.

In [13]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## Random array creation

In [14]:
np.random.random((2, 2))

array([[0.90465937, 0.0694013 ],
       [0.37603464, 0.88298298]])

* * *

# 5\. List vs Array

Python list and NumPy array may look similar, but they are different.

## Python List

- can store different datatypes
    
- slower for numerical operations
    
- consumes more memory
    
- does not support vectorized operations directly
    

## NumPy Array

- stores same datatype elements
    
- faster
    
- memory efficient
    
- supports vectorized mathematical operations
    

## Example

### List


In [15]:
l = [1, 2, 3]
print(l * 2)

[1, 2, 3, 1, 2, 3]


### Array

In [16]:
a = np.array([1, 2, 3])
print(a * 2)

[2 4 6]


## Main differences

| Basis | Python List | NumPy Array |
| --- | --- | --- |
| Datatype | can be mixed | mostly same datatype |
| Speed | slower | faster |
| Memory | more | less |
| Operations | limited | efficient numerical operations |
| Use | general-purpose | numerical computing |

* * *

# 6\. NumPy Attributes

NumPy arrays have many useful attributes.

## a) `ndim`

Tells the number of dimensions.

In [17]:
a = np.array([[1, 2], [3, 4]])
print(a.ndim)

2



## b) `shape`

Tells the size of each dimension.

In [18]:
print(a.shape)

(2, 2)


## c) `size`

Total number of elements.

In [19]:
print(a.size)

4


## d) `dtype`

Datatype of array elements.

In [20]:
print(a.dtype)

int64


## e) `itemsize`

Size of one element in bytes.

In [21]:
print(a.itemsize)

8


## f) `nbytes`

Total bytes consumed by array.

In [22]:
print(a.nbytes)

32


* * *

# 7\. NumPy Operations

NumPy supports element-wise operations.

## Addition

In [24]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)

[5 7 9]


# 8\. NumPy Broadcasting

**Broadcasting** means NumPy can perform arithmetic operations on arrays of different shapes under certain rules.

It automatically expands smaller arrays to match larger arrays without actually copying data.

## Example

In [26]:

a = np.array([1, 2, 3])
b = 2
print(a + b)

[3 4 5]


## Another example

In [27]:
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])
print(a + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


## Broadcasting rules

1.  dimensions must be equal, or
    
2.  one of them must be 1
    

If not, broadcasting gives an error.

### Importance

- avoids loops
    
- faster operations
    
- concise code
    

* * *

# 9\. NumPy Functions

NumPy provides many functions.

## A) String Functions

These are used for arrays of strings.

### Examples

In [28]:
arr = np.array(['hello', 'world'])
print(np.char.upper(arr))
print(np.char.lower(arr))
print(np.char.title(arr))
print(np.char.split(arr))

['HELLO' 'WORLD']
['hello' 'world']
['Hello' 'World']
[list(['hello']) list(['world'])]


### Common string functions

- `np.char.upper()`
    
- `np.char.lower()`
    
- `np.char.title()`
    
- `np.char.split()`
    
- `np.char.strip()`
    
- `np.char.replace()`
    

* * *

## B) Mathematical Functions

Used for arithmetic and scientific calculations.

### Examples

In [29]:
a = np.array([1, 4, 9, 16])
print(np.sqrt(a))
print(np.exp(a))
print(np.sin(a))
print(np.cos(a))
print(np.log(a))

[1. 2. 3. 4.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332]
[ 0.54030231 -0.65364362 -0.91113026 -0.95765948]
[0.         1.38629436 2.19722458 2.77258872]


### Common mathematical functions

- `np.sqrt()`
    
- `np.power()`
    
- `np.exp()`
    
- `np.log()`
    
- `np.sin()`
    
- `np.cos()`
    
- `np.tan()`
    
- `np.abs()`
    

* * *

## C) Statistical Functions

Used to summarize and analyze data.

### Examples

In [30]:
a = np.array([10, 20, 30, 40, 50])
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))
print(np.min(a))
print(np.max(a))

30.0
30.0
14.142135623730951
200.0
10
50


### Common statistical functions

- `np.mean()`
    
- `np.median()`
    
- `np.std()`
    
- `np.var()`
    
- `np.min()`
    
- `np.max()`
    
- `np.sum()`
    

* * *

## D) Sorting Functions

Used to sort data.

### Example

In [31]:
a = np.array([5, 2, 8, 1])
print(np.sort(a))

[1 2 5 8]


### Common sorting functions

- `np.sort()`
    
- `np.argsort()`
    

`argsort()` gives indices of sorted elements.

In [32]:
print(np.argsort(a))

[3 1 0 2]


## E) Searching Functions

Used to search values or conditions.

### Examples


In [33]:
a = np.array([10, 20, 30, 40, 50])
print(np.where(a > 25))
print(np.argmax(a))
print(np.argmin(a))

(array([2, 3, 4]),)
4
0


### Common searching functions

- `np.where()`
    
- `np.argmax()`
    
- `np.argmin()`
    
- `np.nonzero()`
    

* * *

# 10\. NumPy Special Functions

Now let us explain the important special functions you listed.

* * *

## 1) `reshape()`

Used to change the shape of an array without changing data.

### Example

In [34]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print(b)

[[1 2 3]
 [4 5 6]]


### Important point

Total number of elements must remain same.

* * *

## 2) `sum()`

Used to find total sum of elements.

### Example

In [35]:
a = np.array([1, 2, 3, 4])
print(np.sum(a))

10


### Axis-wise sum

In [36]:
b = np.array([[1, 2], [3, 4]])
print(np.sum(b, axis=0))
print(np.sum(b, axis=1))

[4 6]
[3 7]


## 3) `random()`

Used to generate random numbers.

### Example

In [37]:
print(np.random.random((2, 2)))

[[0.27988859 0.6354135 ]
 [0.29528975 0.25120736]]


This creates random floating-point values between 0 and 1.

### Other random functions

In [38]:
np.random.randint(1, 10, size=(2, 3))
np.random.rand(3)

array([0.36849716, 0.96272592, 0.13602759])

* * *

## 4) `zeros()`

Creates an array filled with zeros.

### Example

In [39]:
print(np.zeros((3, 4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]



Output:  
A 3×4 array of all zeros.

### Use

- initialization
    
- placeholders
    
- matrix creation
    

* * *

## 5) `ones()`

Creates an array filled with ones.

### Example

In [40]:
print(np.ones((2, 3)))

[[1. 1. 1.]
 [1. 1. 1.]]



## 6) `mean()`

Used to find average of array elements.

### Example

In [41]:
a = np.array([10, 20, 30, 40])
print(np.mean(a))

25.0


## 7) `dot()`

Used for dot product of vectors or matrix multiplication.

### Example

In [42]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a, b))

32


In [58]:
a = np.array([[1, 2], [3]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

### Matrix example

In [55]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.dot(a, b))

[[19 22]
 [43 50]]


In [57]:
l=[[1,2,3],[4,5]]
print(l)

[[1, 2, 3], [4, 5]]



## 8) `std()`

Used to calculate standard deviation.

### Example

In [44]:
a = np.array([10, 20, 30, 40, 50])
print(np.std(a))

14.142135623730951


### Meaning

Standard deviation shows how spread out the values are from the mean.

* * *

## 9) `empty()`

Creates an uninitialized array.

### Example

In [45]:
print(np.empty((2, 2)))

[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]


### Important point

Values are not guaranteed to be zero. They may contain random existing memory values.

### Use

Useful when performance matters and values will be assigned later.

* * *

## 10) `arange()`

Creates values in a specified interval.

### Syntax

In [47]:
# np.arange(start, stop, step)ॉ
print(np.arange(1, 10, 2))

[1 3 5 7 9]


## 11) `numpy.linspace()`

Creates evenly spaced numbers over a specified interval.

### Syntax

In [49]:
# np.linspace(start, stop, number_of_values)
print(np.linspace(0, 10, 5))

[ 0.   2.5  5.   7.5 10. ]


### Difference between `arange()` and `linspace()`

- `arange()` uses step size
    
- `linspace()` uses number of values
    

* * *

# 11\. Additional Examples of NumPy Usage

## Creating a 1D array

In [50]:
a = np.array([1, 2, 3, 4])


## Creating a 2D array

In [51]:
b = np.array([[1, 2], [3, 4]])

## Multiplying all elements

In [52]:
print(a * 10)

[10 20 30 40]



## Mean and standard deviation

In [53]:
print(np.mean(a))
print(np.std(a))

2.5
1.118033988749895


## Reshaping

In [54]:
print(a.reshape(2, 2))

[[1 2]
 [3 4]]


# 12\. Advantages of NumPy

- high speed
    
- efficient memory use
    
- simple syntax
    
- rich mathematical library
    
- useful for matrices and vectors
    
- basis for Pandas, SciPy, Scikit-learn, and many ML tools
    

* * *

# 13\. Limitations of NumPy

- all elements usually same datatype
    
- not as flexible as Python lists for mixed data
    
- for labeled/tabular data, Pandas is often better


# 14\. Short Exam-Style Definitions

## NumPy

NumPy is a Python library used for numerical and scientific computing. It provides support for large multi-dimensional arrays and many mathematical functions.

## ndarray

An ndarray is the main NumPy array object that stores elements of the same datatype in one or more dimensions.

## Broadcasting

Broadcasting is the process by which NumPy performs arithmetic operations on arrays of different shapes by automatically expanding smaller arrays.

## reshape()

The `reshape()` function changes the shape of an array without changing its data.

## arange()

The `arange()` function creates an array of values within a given range using a fixed step.

## linspace()

The `linspace()` function creates equally spaced values between a start value and an end value.

* * *

# 15\. Summary Table of Important Functions

| Function | Purpose |
| --- | --- |
| `np.array()` | create array |
| `np.zeros()` | array of zeros |
| `np.ones()` | array of ones |
| `np.empty()` | uninitialized array |
| `np.arange()` | range-based array |
| `np.linspace()` | equally spaced values |
| `reshape()` | change array shape |
| `np.sum()` | sum of elements |
| `np.mean()` | average |
| `np.std()` | standard deviation |
| `np.dot()` | dot product |
| `np.random.random()` | random values |

* * *
